### ISSUE TITLE
Select2 not loading cities

### ISSUE THREAD

**Issue by hoekie** [tabuna/tutorial_create_profile_for_orchid#1]
Hi Tabuna,

Great tutorial!
It has given me more insight in how orchid works. Thanks!

I ran into one issue though...

When I want to select a city I get the following error

'The results can not be loaded'

In console:

POST http://orchid.localhost/dashboard/systems/widget/App%5CHttp%5CWidgets%5CCityWidget 404 (Not Found)

It seems that the dashes have been replaced bij %5C.

Do you have any idear to solve this?
Maybe it's because i'm running on windows?

Development environment:
xampp on Windows 10,
PHP 7.2.1

Thanks!

Richard

**Comment by tabuna** [comment]
@hoekie 

Hi Richard, thank you for taking the time to write.
I need some time to fix this problem

**Comment by tabuna** [comment]
You can check that this error is repeated in the dev-master?

**Comment by hoekie** [comment]
Hi Alexandr,

I made a fresh installation of Laravel 5.6 and added the orchid platform dev-master.
Then I copied all the code from your profile tutorial from github to my application.

In AppServiceProvider.php I had to change:

`use App\Http\Composer\MenuComposer;` to
`use App\Http\Composers\MenuComposer;` (Composer**s**)

In MenuComposer I changed the namespace to `App\Http\Composers;`

The profile form appears as expected but when I try to select a city I get the following error:
`POST http://orchid.localhost/dashboard/systems/widget/%02%9AG%B6%DAV%89%D8%1E%B6%C0%A2%B7%%A2v%07%AD 400 (Bad Request)`

Is the above data helpfull to fix the problem?

Let me know if I have to do some more tests on this issue.

Success!

Richard

**Comment by tabuna** [comment]
Hello, I was wrong. dev-master did not work for anyone.
Please check again (dev-master), I'll try, that would not happen again in the future

**Comment by hoekie** [comment]
Works like a charm!

Thanks Alexandr.

Your the best!
